default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV["MYSQL_DB_HOST"] || 'localhost' %>
  username: <%= ENV["MYSQL_ROOT_NAME"] || 'setup' %>
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] || 'secret123' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV["MYSQL_DATABASE"] || 'portal_ledes_api_development' %>

staging:
  <<: *default
  database: <%= ENV["MYSQL_DATABASE"] || 'portal_ledes_api_staging' %>

production:
  <<: *default
  database: <%= ENV["MYSQL_DATABASE"] || 'portal_ledes_api_production' %>
